user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

gladiator:
    resource: "@GladiatorBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

